platform :ios, '7.0'

pod 'MBProgressHUD'
pod 'SIAlertView'
pod 'FXBlurView'
pod 'SDWebImage'
pod 'RevMob'
pod 'RNCryptor'
pod 'Ask4AppReviews'
pod 'RMStore'
pod 'REFrostedViewController'
pod 'TapjoySDK'
pod 'InMobiSDK'
pod 'AdColony'
pod 'UIActivityIndicator-for-SDWebImage'